GRADECARD_SPREADSHEET_ID = "1HPl-eqBKV1USQv5EBNejB7hAt32QxbVLquRa6OISbdI"

BASE_STUDENT_SPREADSHEET_ID = "19Hd6Zl7yfs03xoxFYw-yLXQR9eVrAAJhVD1BjM6dJDw"
STUDENT_CARDS_FOLDER_ID = "1deoHV0Z9Qi4syUYusJZj1jGLhv1jabmA"

BASE_TA_SPREADSHEET_ID = None
TA_CARDS_FOLDER_ID = None

GRADESCOPE_COURSE_ID = ""
